version: '3.6'

services:

  elasticsearch:
    image: elasticsearch:7.9.3
    container_name: els
    environment: 
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:7.9.3
    container_name: elk
    environment: 
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
    ports:
      - "5601:5601"

networks:
  default:
    external:
      name: elastic